import { Component } from '@angular/core';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrl: './menu.component.css'
})
export class MenuComponent {
  menuItems = [
    { category: 'Coffee', items: [
      { name: 'Filter Coffee', price: 3.50 },
      { name: 'Chai Latte', price: 4.00 },
      { name: 'Masala Coffee', price: 4.50 },
      { name: 'Turmeric Latte', price: 4.00 },
      { name: 'Cardamom Coffee', price: 4.50 },
      { name: 'Ginger Coffee', price: 4.00 },
      { name: 'Chocolate Chai', price: 4.50 },
      { name: 'Coconut Coffee', price: 5.00 },
      { name: 'Hazelnut Chai', price: 4.50 },
      { name: 'Mint Coffee', price: 4.00 },
      { name: 'Vanilla Chai', price: 4.50 },
      { name: 'Cinnamon Coffee', price: 4.00 },
      { name: 'Almond Chai', price: 4.50 },
      { name: 'Rose Coffee', price: 5.00 },
      { name: 'Saffron Latte', price: 5.50 },
      {name:'Americano',price:6.50},
      {name:'Iced Coffee',price:7.50},
      {name:'Cappuccino',price:8.50},
      // Add more coffee items as needed
    ]},
    { category: 'Desserts', items: [
      { name: 'Chocolate Cake', price: 4.50 },
      { name: 'Cheesecake', price: 5.00 },
      { name: 'Tiramisu', price: 6.50 },
      { name: 'Gulab Jamun', price: 3.50 },
      { name: 'Jalebi', price: 4.00 },
      { name: 'Rasgulla', price: 4.50 },
      { name: 'Kheer', price: 5.00 },
      { name: 'Halwa', price: 3.00 },
      { name: 'Ladoo', price: 3.50 },
      { name: 'Barfi', price: 4.50 },
      { name: 'Rasmalai', price: 5.50 },
      { name: 'Gajar Ka Halwa', price: 4.50 },
      { name: 'Mysore Pak', price: 5.00 },
      { name: 'Malpua', price: 4.00 },
      { name: 'Shahi Tukda', price: 5.50 },
      { name: 'Sandesh', price: 4.00 },
      { name: 'Cham Cham', price: 4.50 },
      { name: 'Peda', price: 3.50 },
    ]},
    { category: 'Snacks', items: [
      { name: 'French Fries', price: 3.00 },
      { name: 'Chicken Wings', price: 6.50 },
      { name: 'Nachos', price: 5.00 },
      { name: 'Samosa', price: 2.50 },
      { name: 'Pakora', price: 3.00 },
      { name: 'Bhel Puri', price: 3.50 },
      { name: 'Aloo Tikki', price: 4.00 },
      { name: 'Pani Puri', price: 4.50 },
      { name: 'Dahi Puri', price: 5.00 },
      { name: 'Vada Pav', price: 3.50 },
      { name: 'Paneer Tikka', price: 5.50 },
      { name: 'Dhokla', price: 4.50 },
      { name: 'Chaat Papri', price: 3.00 },
      { name: 'Kachori', price: 4.50 },
      { name: 'Khandvi', price: 5.00 },
      { name: 'Aloo Chaat', price: 4.00 },
      { name: 'Murmura Chivda', price: 3.50 },
      { name: 'Masala Puri', price: 4.50 },
    ]},
    { category: 'Mocktails', items: [
      { name: 'Virgin Mojito', price: 4.00 },
      { name: 'Berry Blast', price: 5.50 },
      { name: 'Tropical Punch', price: 4.50 },
      { name: 'Masala Lemonade', price: 3.50 },
      { name: 'Spiced Buttermilk', price: 3.00 },
      { name: 'Rose Sharbat', price: 4.50 },
      { name: 'Thandai', price: 5.00 },
      { name: 'Kokum Sherbet', price: 3.50 },
      { name: 'Cucumber Mint Cooler', price: 4.50 },
      { name: 'Ginger Fizz', price: 4.00 },
      { name: 'Aam Panna', price: 4.50 },
      { name: 'Chai Masala Smoothie', price: 5.00 },
      { name: 'Strawberry Daiquiri', price: 5.00 },
      { name: 'Mint Julep', price: 4.50 },
      { name: 'Mai Tai', price: 6.00 },
      { name: 'Margarita', price: 5.50 },
      { name: 'Blue Lagoon', price: 5.00 },
      { name: 'Mint Lemonade', price: 4.50 },
      
    ]},
    // Add more categories as needed
    { category: 'Mains', items: [
      { name: 'Paneer Butter Masala', price: 8.00 },
      { name: 'Chicken Curry', price: 10.50 },
      { name: 'Dal Tadka', price: 7.50 },
      { name: 'Biryani', price: 12.00 },
      { name: 'Butter Chicken', price: 11.50 },
      { name: 'Chole Bhature', price: 9.00 },
      { name: 'Palak Paneer', price: 8.50 },
      { name: 'Rajma Chawal', price: 7.00 },
      { name: 'Aloo Gobi', price: 8.00 },
      { name: 'Fish Curry', price: 12.50 },
      { name: 'Mutton Curry', price: 13.50 },
      { name: 'Vegetable Biryani', price: 10.00 },
      { name: 'Chicken Biryani', price: 11.00 },
      { name: 'Samosa Chaat', price: 6.50 },
      { name: 'Mushroom Masala', price: 9.50 },
      { name: 'Tandoori Roti', price: 2.50 },
      { name: 'Naan', price: 3.00 },
      { name: 'Chicken Korma', price: 12.00 },
     
  ]},
    
   ]}